Feature/route between two points
PyLadiesMadrid/pycartociudad pull request #14
Opened 2020-10-18 18:43 UTC by beatrizgoa

2020-10-24 09:21 UTC, koldLight requested changes
He puesto un par de comentarios :)

2020-10-24 09:21 UTC, koldLight commented on pycartociudad/route_between_two_points.py
> +                  f'&locale=es&vehicle={"CAR" if vehicle else "WALK"}'
En el parámetro `dest` estás metiendo `lat_init`.

2020-10-24 09:21 UTC, koldLight commented on pycartociudad/route_between_two_points.py
> +                         for item in instructions_raw]
Aquí quizás se pierde mucha parte interesante de la salida. Está bien que la simplifiques, pero hay cosas que pueden venir bien según la aplicación que se le de, como:

* En cada "paso", su origen y su destino
* La distancia de cada paso, en un integer (ahora habría que parsearlo del string junto con la descripción)
* El tiempo total de ruta
* La distancia total de ruta
* etc...

Entonces, quizás intentaría simplificar la salida pero sin perder campos (o al menos los que puedan ser interesantes). Echándole un vistazo de primeras a la petición de [ejemplo](http://www.cartociudad.es/services/api/route?orig=39.487681,-0.373106&dest=39.484336,-0.358171&locale=es&vehicle=CAR) quizás lo único que haría por ahora es no anidar el array `instruction` dentro de `instructionsData` y devolverlo un nivel más arriba.

2020-10-26 20:43 UTC, koldLight commented on pycartociudad/route_between_two_points.py
> +                  f'&locale=es&vehicle={"CAR" if vehicle else "WALK"}'
Veo que está corregido, cierro este comentario :)

2020-11-21 11:30 UTC, beatrizgoa commented on pycartociudad/route_between_two_points.py
> +                         for item in instructions_raw]
Hola ! no entiendo muy bien lo de animar el array de instruction dentro de `instructionsData`, porque dentro de `instructionsData`, solo está `instructions` (para explicarme mejor):
```
json.loads(request_result.text)['instructionsData'].keys()
Out[3]: dict_keys(['instruction'])
```
Creo que te podría referir a devolver todo:
```
json.loads(request_result.text).keys()
Out[4]: dict_keys(['bbox', 'distance', 'found', 'from', 'geom', 'info', 'instructionsData', 'time', 'to'])
```
para que no se pierda info, podria ser?

2020-11-21 12:09 UTC, merged

2020-11-21 12:09 UTC, koldLight commented
Lo veo muy bien, gracias! Se devuelve la info completa de la petición y además se convierte la distancia a float que tiene más sentido que string como viene de la API